#!/bin/bash

dotfiles_path="/home/x4192/Repos/madgrid/dot"
home_path="/home/x4192"

# List of dot files and their corresponding destination paths
files=(
    "screen/.screenrc"
    "tmux/.tmux.conf"
    "vim/.vimrc"
    "lynx/lynx.lss"
    "lynx/lynx.cfg"
    "bash/.bashrc"
)

# Create symbolic links
for file in "${files[@]}"; do
    source_file="$dotfiles_path/$file"
    destination_file="$home_path/${file##*/}"  # Get the filename without the preceding directory path
    
    if [[ $file == *"lynx"* ]]; then
        # For lynx, create the .config/lynx folder if it doesn't exist
        mkdir -p "$home_path/.config/lynx"
        destination_file="$home_path/.config/${file##*/}"
    fi

    ln -s "$source_file" "$destination_file"
    echo "Created symlink: $destination_file"
done

# Create ~/.fonts directory and copy *.ttf files
mkdir -p "$home_path/.fonts"
cp "$dotfiles_path/fonts"/*.ttf "$home_path/.fonts/"

# Run fc-cache
fc-cache -fv

echo "Setup completed!"

