kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: development
networking:
nodes:
- role: control-plane
  # https://github.com/kubernetes-sigs/kind/issues/1416#issuecomment-600438973
  # https://kind.sigs.k8s.io/docs/user/configuration/#extra-mounts	  
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
  # To enable Ingress this port-mapping is required
  # https://kind.sigs.k8s.io/docs/user/configuration/#extra-port-mappings
  extraPortMappings:  
  - containerPort: 80 
    hostPort: 8080
